#!/bin/bash

rm -rf aclocal.m4 autom4te.cache/ config.* configure depcomp install-sh \
 libtool ltmain.sh Makefile Makefile.in missing mkinstalldirs

find . \( \
       \( -name .libs -prune \) \
    -o \( -name .deps -prune \) \
    -o -name Makefile.in \
    -o -name Makefile \
    -o -name \*.o \
    -o -name \*.lo \
    -o -name \*.la \) \
    -exec rm -rf {} \;

