%define prefix /usr

Name:          libopenmodeller
License:       GPL
Group:         Libraries/Research
Autoreqprov:   on
Version:       0.6.0
Release:       0
Source:        %{name}-src-%{version}.tar.gz
Url:           http://openmodeller.sf.net
Summary:       Library for Potential Distribution Modelling
BuildRoot:     %{_tmppath}/%{name}-%{version}-build
BuildRequires: cmake

%description
openModeller is an open source C++ static spatial distribution modelling 
library which is mainly being used to predict species distribution 
(fundamental niche). Models are generated by algorithms that receive as 
input a set of occurrence points (latitude/longitude/abundance) and a 
set of raster files. Models can then be projected in different 
environments (different set of raster files) to generate distribution 
maps. Available algorithms include Bioclim, GARP (with best subset 
procedure), CSM (Climate Space Model), and cartesian distance algorithms. 
New algorithms can easily be added. The library uses GDAL to read 
different raster formats and proj4 to convert between different 
coordinate systems and projections. A console interface is distributed 
with the library, as well as a SWIG wrapper for the Python language and 
a SOAP server prototype. The tool was originally developed by CRIA as 
part of the speciesLink project (funded by Fapesp, the State of Sao 
Paulo Research Foundation). During its history, other major contributors 
like the University of Reading (BDWorld project), the University of 
Kansas, and other individual participants joined the effort and became 
active developers.

%package devel
Group:      Development/Libraries/C and C++
Summary:    Potential Distribution Modelling Library - Development Files
Requires:   expat
Requires:   proj >= 4.5.0
Requires:   gdal >= 1.4.2
Requires:   libcurl >= 7.15.4
Requires:   sqlite >= 3.3.6
Requires:   gsl >= 1.4
Requires:   boost >= 1.31
Requires:   gcc-g77

%description devel
Include files and libraries to link programs against openModeller
or develop new algorithms. 

%package -n openmodeller-tools
Group:      Applications/Research
Summary:    Potential Distribution Modelling Library - Console Tools
Requires:   %{name} >= %{version}
Requires:   X11-libs

%description -n openmodeller-tools
Console and command-line tools for using openModeller.

%define srcdirname %{name}-src-%{version}

%prep
%setup -q -n %{srcdirname}

%build
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=%{prefix} ../
make

%install
rm -rf $RPM_BUILD_ROOT
make install

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root)
%{_libdir}/libopenmodeller.so.*
%dir %{_libdir}/openmodeller
%{_libdir}/openmodeller/*so*
%doc AUTHORS COPYING.txt ChangeLog README.txt INSTALL NEWS

%files devel
%defattr(-,root,root)
%{_libdir}/libopenmodeller.*a
%{_libdir}/libopenmodeller.so
%{_libdir}/openmodeller/*a
%dir %{prefix}/include/openmodeller
%{prefix}/include/openmodeller

%files -n openmodeller-tools
%defattr(-,root,root)
/usr/bin/*

%changelog -n libopenmodeller
* Mon Jun 23 2008 - Renato De Giovanni <renato [at] cria . org . br>
- renamed openmodeller package to openmodeller-tools
- replaced automake commands by cmake ones
* Mon May 13 2008 - Renato De Giovanni <renato [at] cria . org . br>
- removed libopenmodellerxml files
* Mon Nov 27 2006 - Renato De Giovanni <renato [at] cria . org . br>
- included missing libopenmodellerxml files
* Thu Jul 21 2005 - Jens Oberender <j.obi@troja.net>
- renamed to libopenmodeller
- splitted up openmodeller for the tools
* Wed Mar 24 2004 - Jens Oberender <j.obi@troja.net>
- initial build
