/* soapH.h
   Generated by gSOAP 2.5.2 from om_soap.hh
   Copyright (C) 2001-2004 Genivia, Inc. All Rights Reserved.
   This software is released under the gSOAP public license and GPL.
   See README.txt for further details.
*/
#ifndef soapH_H
#define soapH_H
#include "soapStub.h"

SOAP_BEGIN_NAMESPACE(soap)
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void * SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putattachments(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getattachments(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);

SOAP_FMAC3 void SOAP_FMAC4 soap_fdelete(struct soap_clist*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_byte(struct soap*, char const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_xsd__int
#define SOAP_TYPE_xsd__int (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__int(struct soap*, int *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__int(struct soap*, int const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_xsd__int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_xsd__int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_int(struct soap*, int const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_xsd__double
#define SOAP_TYPE_xsd__double (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__double(struct soap*, double *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__double(struct soap*, double const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__double(struct soap*, double *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_get_xsd__double(struct soap*, double *, const char*, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in_xsd__double(struct soap*, const char*, double *, const char*);

#ifndef SOAP_TYPE_double
#define SOAP_TYPE_double (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_double(struct soap*, double *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_double(struct soap*, double const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_double(struct soap*, double *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_get_double(struct soap*, double *, const char*, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in_double(struct soap*, const char*, double *, const char*);

#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_unsignedByte(struct soap*, unsigned char const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, unsigned char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_unsignedInt(struct soap*, unsigned int const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (59)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__base64Binary(struct soap*, const char*, int, const xsd__base64Binary *, const char*);
SOAP_FMAC3 xsd__base64Binary * SOAP_FMAC4 soap_get_xsd__base64Binary(struct soap*, xsd__base64Binary *, const char*, const char*);
SOAP_FMAC3 xsd__base64Binary * SOAP_FMAC4 soap_in_xsd__base64Binary(struct soap*, const char*, xsd__base64Binary *, const char*);

SOAP_FMAC5 xsd__base64Binary * SOAP_FMAC6 soap_new_xsd__base64Binary(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__base64Binary(struct soap*, xsd__base64Binary*);
SOAP_FMAC5 xsd__base64Binary * SOAP_FMAC6 soap_instantiate_xsd__base64Binary(struct soap*, int, const char*, const char*, size_t*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (77)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (76)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (75)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef SOAP_TYPE_om__ping
#define SOAP_TYPE_om__ping (74)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_om__ping(struct soap*, struct om__ping const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_om__ping(struct soap*, const struct om__ping *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_om__ping(struct soap*, struct om__ping *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_om__ping(struct soap*, struct om__ping *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_om__ping(struct soap*, const char*, int, const struct om__ping *, const char*);
SOAP_FMAC3 struct om__ping * SOAP_FMAC4 soap_get_om__ping(struct soap*, struct om__ping *, const char*, const char*);
SOAP_FMAC3 struct om__ping * SOAP_FMAC4 soap_in_om__ping(struct soap*, const char*, struct om__ping *, const char*);

#ifndef SOAP_TYPE_om__pingResponse
#define SOAP_TYPE_om__pingResponse (73)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_om__pingResponse(struct soap*, struct om__pingResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_om__pingResponse(struct soap*, const struct om__pingResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_om__pingResponse(struct soap*, struct om__pingResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_om__pingResponse(struct soap*, struct om__pingResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_om__pingResponse(struct soap*, const char*, int, const struct om__pingResponse *, const char*);
SOAP_FMAC3 struct om__pingResponse * SOAP_FMAC4 soap_get_om__pingResponse(struct soap*, struct om__pingResponse *, const char*, const char*);
SOAP_FMAC3 struct om__pingResponse * SOAP_FMAC4 soap_in_om__pingResponse(struct soap*, const char*, struct om__pingResponse *, const char*);

#ifndef SOAP_TYPE_om__getDistributionMap
#define SOAP_TYPE_om__getDistributionMap (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_om__getDistributionMap(struct soap*, struct om__getDistributionMap const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_om__getDistributionMap(struct soap*, const struct om__getDistributionMap *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_om__getDistributionMap(struct soap*, struct om__getDistributionMap *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_om__getDistributionMap(struct soap*, struct om__getDistributionMap *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_om__getDistributionMap(struct soap*, const char*, int, const struct om__getDistributionMap *, const char*);
SOAP_FMAC3 struct om__getDistributionMap * SOAP_FMAC4 soap_get_om__getDistributionMap(struct soap*, struct om__getDistributionMap *, const char*, const char*);
SOAP_FMAC3 struct om__getDistributionMap * SOAP_FMAC4 soap_in_om__getDistributionMap(struct soap*, const char*, struct om__getDistributionMap *, const char*);

#ifndef SOAP_TYPE_om__getDistributionMapResponse
#define SOAP_TYPE_om__getDistributionMapResponse (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_om__getDistributionMapResponse(struct soap*, struct om__getDistributionMapResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_om__getDistributionMapResponse(struct soap*, const struct om__getDistributionMapResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_om__getDistributionMapResponse(struct soap*, struct om__getDistributionMapResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_om__getDistributionMapResponse(struct soap*, struct om__getDistributionMapResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_om__getDistributionMapResponse(struct soap*, const char*, int, const struct om__getDistributionMapResponse *, const char*);
SOAP_FMAC3 struct om__getDistributionMapResponse * SOAP_FMAC4 soap_get_om__getDistributionMapResponse(struct soap*, struct om__getDistributionMapResponse *, const char*, const char*);
SOAP_FMAC3 struct om__getDistributionMapResponse * SOAP_FMAC4 soap_in_om__getDistributionMapResponse(struct soap*, const char*, struct om__getDistributionMapResponse *, const char*);

SOAP_FMAC5 struct om__getDistributionMapResponse * SOAP_FMAC6 soap_new_om__getDistributionMapResponse(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_om__getDistributionMapResponse(struct soap*, struct om__getDistributionMapResponse*);
SOAP_FMAC5 struct om__getDistributionMapResponse * SOAP_FMAC6 soap_instantiate_om__getDistributionMapResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_om__createModel
#define SOAP_TYPE_om__createModel (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_om__createModel(struct soap*, struct om__createModel const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_om__createModel(struct soap*, const struct om__createModel *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_om__createModel(struct soap*, struct om__createModel *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_om__createModel(struct soap*, struct om__createModel *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_om__createModel(struct soap*, const char*, int, const struct om__createModel *, const char*);
SOAP_FMAC3 struct om__createModel * SOAP_FMAC4 soap_get_om__createModel(struct soap*, struct om__createModel *, const char*, const char*);
SOAP_FMAC3 struct om__createModel * SOAP_FMAC4 soap_in_om__createModel(struct soap*, const char*, struct om__createModel *, const char*);

#ifndef SOAP_TYPE_om__createModelResponse
#define SOAP_TYPE_om__createModelResponse (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_om__createModelResponse(struct soap*, struct om__createModelResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_om__createModelResponse(struct soap*, const struct om__createModelResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_om__createModelResponse(struct soap*, struct om__createModelResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_om__createModelResponse(struct soap*, struct om__createModelResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_om__createModelResponse(struct soap*, const char*, int, const struct om__createModelResponse *, const char*);
SOAP_FMAC3 struct om__createModelResponse * SOAP_FMAC4 soap_get_om__createModelResponse(struct soap*, struct om__createModelResponse *, const char*, const char*);
SOAP_FMAC3 struct om__createModelResponse * SOAP_FMAC4 soap_in_om__createModelResponse(struct soap*, const char*, struct om__createModelResponse *, const char*);

#ifndef SOAP_TYPE_om__Output
#define SOAP_TYPE_om__Output (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_om__Output(struct soap*, struct soap_Output const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_om__Output(struct soap*, const struct soap_Output *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_om__Output(struct soap*, struct soap_Output *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_om__Output(struct soap*, struct soap_Output *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_om__Output(struct soap*, const char*, int, const struct soap_Output *, const char*);
SOAP_FMAC3 struct soap_Output * SOAP_FMAC4 soap_get_om__Output(struct soap*, struct soap_Output *, const char*, const char*);
SOAP_FMAC3 struct soap_Output * SOAP_FMAC4 soap_in_om__Output(struct soap*, const char*, struct soap_Output *, const char*);

#ifndef SOAP_TYPE_soap_Output
#define SOAP_TYPE_soap_Output (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_soap_Output(struct soap*, struct soap_Output const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_soap_Output(struct soap*, const struct soap_Output *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_soap_Output(struct soap*, struct soap_Output *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_soap_Output(struct soap*, struct soap_Output *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_soap_Output(struct soap*, const char*, int, const struct soap_Output *, const char*);
SOAP_FMAC3 struct soap_Output * SOAP_FMAC4 soap_get_soap_Output(struct soap*, struct soap_Output *, const char*, const char*);
SOAP_FMAC3 struct soap_Output * SOAP_FMAC4 soap_in_soap_Output(struct soap*, const char*, struct soap_Output *, const char*);

#ifndef SOAP_TYPE_om__Algorithm
#define SOAP_TYPE_om__Algorithm (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_om__Algorithm(struct soap*, struct soap_Algorithm const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_om__Algorithm(struct soap*, const struct soap_Algorithm *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_om__Algorithm(struct soap*, struct soap_Algorithm *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_om__Algorithm(struct soap*, struct soap_Algorithm *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_om__Algorithm(struct soap*, const char*, int, const struct soap_Algorithm *, const char*);
SOAP_FMAC3 struct soap_Algorithm * SOAP_FMAC4 soap_get_om__Algorithm(struct soap*, struct soap_Algorithm *, const char*, const char*);
SOAP_FMAC3 struct soap_Algorithm * SOAP_FMAC4 soap_in_om__Algorithm(struct soap*, const char*, struct soap_Algorithm *, const char*);

#ifndef SOAP_TYPE_soap_Algorithm
#define SOAP_TYPE_soap_Algorithm (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_soap_Algorithm(struct soap*, struct soap_Algorithm const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_soap_Algorithm(struct soap*, const struct soap_Algorithm *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_soap_Algorithm(struct soap*, struct soap_Algorithm *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_soap_Algorithm(struct soap*, struct soap_Algorithm *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_soap_Algorithm(struct soap*, const char*, int, const struct soap_Algorithm *, const char*);
SOAP_FMAC3 struct soap_Algorithm * SOAP_FMAC4 soap_get_soap_Algorithm(struct soap*, struct soap_Algorithm *, const char*, const char*);
SOAP_FMAC3 struct soap_Algorithm * SOAP_FMAC4 soap_in_soap_Algorithm(struct soap*, const char*, struct soap_Algorithm *, const char*);

#ifndef SOAP_TYPE_om__Parameter
#define SOAP_TYPE_om__Parameter (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_om__Parameter(struct soap*, struct soap_Parameter const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_om__Parameter(struct soap*, const struct soap_Parameter *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_om__Parameter(struct soap*, struct soap_Parameter *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_om__Parameter(struct soap*, struct soap_Parameter *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_om__Parameter(struct soap*, const char*, int, const struct soap_Parameter *, const char*);
SOAP_FMAC3 struct soap_Parameter * SOAP_FMAC4 soap_get_om__Parameter(struct soap*, struct soap_Parameter *, const char*, const char*);
SOAP_FMAC3 struct soap_Parameter * SOAP_FMAC4 soap_in_om__Parameter(struct soap*, const char*, struct soap_Parameter *, const char*);

#ifndef SOAP_TYPE_soap_Parameter
#define SOAP_TYPE_soap_Parameter (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_soap_Parameter(struct soap*, struct soap_Parameter const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_soap_Parameter(struct soap*, const struct soap_Parameter *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_soap_Parameter(struct soap*, struct soap_Parameter *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_soap_Parameter(struct soap*, struct soap_Parameter *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_soap_Parameter(struct soap*, const char*, int, const struct soap_Parameter *, const char*);
SOAP_FMAC3 struct soap_Parameter * SOAP_FMAC4 soap_get_soap_Parameter(struct soap*, struct soap_Parameter *, const char*, const char*);
SOAP_FMAC3 struct soap_Parameter * SOAP_FMAC4 soap_in_soap_Parameter(struct soap*, const char*, struct soap_Parameter *, const char*);

#ifndef SOAP_TYPE_om__Mask
#define SOAP_TYPE_om__Mask (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_om__Mask(struct soap*, struct soap_Mask const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_om__Mask(struct soap*, const struct soap_Mask *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_om__Mask(struct soap*, struct soap_Mask *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_om__Mask(struct soap*, struct soap_Mask *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_om__Mask(struct soap*, const char*, int, const struct soap_Mask *, const char*);
SOAP_FMAC3 struct soap_Mask * SOAP_FMAC4 soap_get_om__Mask(struct soap*, struct soap_Mask *, const char*, const char*);
SOAP_FMAC3 struct soap_Mask * SOAP_FMAC4 soap_in_om__Mask(struct soap*, const char*, struct soap_Mask *, const char*);

#ifndef SOAP_TYPE_soap_Mask
#define SOAP_TYPE_soap_Mask (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_soap_Mask(struct soap*, struct soap_Mask const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_soap_Mask(struct soap*, const struct soap_Mask *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_soap_Mask(struct soap*, struct soap_Mask *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_soap_Mask(struct soap*, struct soap_Mask *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_soap_Mask(struct soap*, const char*, int, const struct soap_Mask *, const char*);
SOAP_FMAC3 struct soap_Mask * SOAP_FMAC4 soap_get_soap_Mask(struct soap*, struct soap_Mask *, const char*, const char*);
SOAP_FMAC3 struct soap_Mask * SOAP_FMAC4 soap_in_soap_Mask(struct soap*, const char*, struct soap_Mask *, const char*);

#ifndef SOAP_TYPE_om__Maps
#define SOAP_TYPE_om__Maps (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_om__Maps(struct soap*, struct soap_Maps const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_om__Maps(struct soap*, const struct soap_Maps *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_om__Maps(struct soap*, struct soap_Maps *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_om__Maps(struct soap*, struct soap_Maps *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_om__Maps(struct soap*, const char*, int, const struct soap_Maps *, const char*);
SOAP_FMAC3 struct soap_Maps * SOAP_FMAC4 soap_get_om__Maps(struct soap*, struct soap_Maps *, const char*, const char*);
SOAP_FMAC3 struct soap_Maps * SOAP_FMAC4 soap_in_om__Maps(struct soap*, const char*, struct soap_Maps *, const char*);

#ifndef SOAP_TYPE_soap_Maps
#define SOAP_TYPE_soap_Maps (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_soap_Maps(struct soap*, struct soap_Maps const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_soap_Maps(struct soap*, const struct soap_Maps *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_soap_Maps(struct soap*, struct soap_Maps *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_soap_Maps(struct soap*, struct soap_Maps *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_soap_Maps(struct soap*, const char*, int, const struct soap_Maps *, const char*);
SOAP_FMAC3 struct soap_Maps * SOAP_FMAC4 soap_get_soap_Maps(struct soap*, struct soap_Maps *, const char*, const char*);
SOAP_FMAC3 struct soap_Maps * SOAP_FMAC4 soap_in_soap_Maps(struct soap*, const char*, struct soap_Maps *, const char*);

#ifndef SOAP_TYPE_om__Map
#define SOAP_TYPE_om__Map (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_om__Map(struct soap*, struct soap_Map const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_om__Map(struct soap*, const struct soap_Map *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_om__Map(struct soap*, struct soap_Map *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_om__Map(struct soap*, struct soap_Map *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_om__Map(struct soap*, const char*, int, const struct soap_Map *, const char*);
SOAP_FMAC3 struct soap_Map * SOAP_FMAC4 soap_get_om__Map(struct soap*, struct soap_Map *, const char*, const char*);
SOAP_FMAC3 struct soap_Map * SOAP_FMAC4 soap_in_om__Map(struct soap*, const char*, struct soap_Map *, const char*);

#ifndef SOAP_TYPE_soap_Map
#define SOAP_TYPE_soap_Map (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_soap_Map(struct soap*, struct soap_Map const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_soap_Map(struct soap*, const struct soap_Map *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_soap_Map(struct soap*, struct soap_Map *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_soap_Map(struct soap*, struct soap_Map *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_soap_Map(struct soap*, const char*, int, const struct soap_Map *, const char*);
SOAP_FMAC3 struct soap_Map * SOAP_FMAC4 soap_get_soap_Map(struct soap*, struct soap_Map *, const char*, const char*);
SOAP_FMAC3 struct soap_Map * SOAP_FMAC4 soap_in_soap_Map(struct soap*, const char*, struct soap_Map *, const char*);

#ifndef SOAP_TYPE_om__Points
#define SOAP_TYPE_om__Points (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_om__Points(struct soap*, struct soap_Points const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_om__Points(struct soap*, const struct soap_Points *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_om__Points(struct soap*, struct soap_Points *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_om__Points(struct soap*, struct soap_Points *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_om__Points(struct soap*, const char*, int, const struct soap_Points *, const char*);
SOAP_FMAC3 struct soap_Points * SOAP_FMAC4 soap_get_om__Points(struct soap*, struct soap_Points *, const char*, const char*);
SOAP_FMAC3 struct soap_Points * SOAP_FMAC4 soap_in_om__Points(struct soap*, const char*, struct soap_Points *, const char*);

#ifndef SOAP_TYPE_soap_Points
#define SOAP_TYPE_soap_Points (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_soap_Points(struct soap*, struct soap_Points const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_soap_Points(struct soap*, const struct soap_Points *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_soap_Points(struct soap*, struct soap_Points *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_soap_Points(struct soap*, struct soap_Points *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_soap_Points(struct soap*, const char*, int, const struct soap_Points *, const char*);
SOAP_FMAC3 struct soap_Points * SOAP_FMAC4 soap_get_soap_Points(struct soap*, struct soap_Points *, const char*, const char*);
SOAP_FMAC3 struct soap_Points * SOAP_FMAC4 soap_in_soap_Points(struct soap*, const char*, struct soap_Points *, const char*);

#ifndef SOAP_TYPE_om__AbsencePoints
#define SOAP_TYPE_om__AbsencePoints (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_om__AbsencePoints(struct soap*, struct soap_AbsencePoints const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_om__AbsencePoints(struct soap*, const struct soap_AbsencePoints *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_om__AbsencePoints(struct soap*, struct soap_AbsencePoints *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_om__AbsencePoints(struct soap*, struct soap_AbsencePoints *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_om__AbsencePoints(struct soap*, const char*, int, const struct soap_AbsencePoints *, const char*);
SOAP_FMAC3 struct soap_AbsencePoints * SOAP_FMAC4 soap_get_om__AbsencePoints(struct soap*, struct soap_AbsencePoints *, const char*, const char*);
SOAP_FMAC3 struct soap_AbsencePoints * SOAP_FMAC4 soap_in_om__AbsencePoints(struct soap*, const char*, struct soap_AbsencePoints *, const char*);

#ifndef SOAP_TYPE_soap_AbsencePoints
#define SOAP_TYPE_soap_AbsencePoints (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_soap_AbsencePoints(struct soap*, struct soap_AbsencePoints const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_soap_AbsencePoints(struct soap*, const struct soap_AbsencePoints *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_soap_AbsencePoints(struct soap*, struct soap_AbsencePoints *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_soap_AbsencePoints(struct soap*, struct soap_AbsencePoints *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_soap_AbsencePoints(struct soap*, const char*, int, const struct soap_AbsencePoints *, const char*);
SOAP_FMAC3 struct soap_AbsencePoints * SOAP_FMAC4 soap_get_soap_AbsencePoints(struct soap*, struct soap_AbsencePoints *, const char*, const char*);
SOAP_FMAC3 struct soap_AbsencePoints * SOAP_FMAC4 soap_in_soap_AbsencePoints(struct soap*, const char*, struct soap_AbsencePoints *, const char*);

#ifndef SOAP_TYPE_om__PresencePoints
#define SOAP_TYPE_om__PresencePoints (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_om__PresencePoints(struct soap*, struct soap_PresencePoints const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_om__PresencePoints(struct soap*, const struct soap_PresencePoints *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_om__PresencePoints(struct soap*, struct soap_PresencePoints *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_om__PresencePoints(struct soap*, struct soap_PresencePoints *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_om__PresencePoints(struct soap*, const char*, int, const struct soap_PresencePoints *, const char*);
SOAP_FMAC3 struct soap_PresencePoints * SOAP_FMAC4 soap_get_om__PresencePoints(struct soap*, struct soap_PresencePoints *, const char*, const char*);
SOAP_FMAC3 struct soap_PresencePoints * SOAP_FMAC4 soap_in_om__PresencePoints(struct soap*, const char*, struct soap_PresencePoints *, const char*);

#ifndef SOAP_TYPE_soap_PresencePoints
#define SOAP_TYPE_soap_PresencePoints (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_soap_PresencePoints(struct soap*, struct soap_PresencePoints const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_soap_PresencePoints(struct soap*, const struct soap_PresencePoints *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_soap_PresencePoints(struct soap*, struct soap_PresencePoints *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_soap_PresencePoints(struct soap*, struct soap_PresencePoints *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_soap_PresencePoints(struct soap*, const char*, int, const struct soap_PresencePoints *, const char*);
SOAP_FMAC3 struct soap_PresencePoints * SOAP_FMAC4 soap_get_soap_PresencePoints(struct soap*, struct soap_PresencePoints *, const char*, const char*);
SOAP_FMAC3 struct soap_PresencePoints * SOAP_FMAC4 soap_in_soap_PresencePoints(struct soap*, const char*, struct soap_PresencePoints *, const char*);

#ifndef SOAP_TYPE_om__Point
#define SOAP_TYPE_om__Point (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_om__Point(struct soap*, struct soap_Point const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_om__Point(struct soap*, const struct soap_Point *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_om__Point(struct soap*, struct soap_Point *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_om__Point(struct soap*, struct soap_Point *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_om__Point(struct soap*, const char*, int, const struct soap_Point *, const char*);
SOAP_FMAC3 struct soap_Point * SOAP_FMAC4 soap_get_om__Point(struct soap*, struct soap_Point *, const char*, const char*);
SOAP_FMAC3 struct soap_Point * SOAP_FMAC4 soap_in_om__Point(struct soap*, const char*, struct soap_Point *, const char*);

#ifndef SOAP_TYPE_soap_Point
#define SOAP_TYPE_soap_Point (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_soap_Point(struct soap*, struct soap_Point const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_soap_Point(struct soap*, const struct soap_Point *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_soap_Point(struct soap*, struct soap_Point *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_soap_Point(struct soap*, struct soap_Point *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_soap_Point(struct soap*, const char*, int, const struct soap_Point *, const char*);
SOAP_FMAC3 struct soap_Point * SOAP_FMAC4 soap_get_soap_Point(struct soap*, struct soap_Point *, const char*, const char*);
SOAP_FMAC3 struct soap_Point * SOAP_FMAC4 soap_in_soap_Point(struct soap*, const char*, struct soap_Point *, const char*);

#ifndef SOAP_TYPE_om__getAlgorithms
#define SOAP_TYPE_om__getAlgorithms (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_om__getAlgorithms(struct soap*, struct om__getAlgorithms const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_om__getAlgorithms(struct soap*, const struct om__getAlgorithms *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_om__getAlgorithms(struct soap*, struct om__getAlgorithms *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_om__getAlgorithms(struct soap*, struct om__getAlgorithms *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_om__getAlgorithms(struct soap*, const char*, int, const struct om__getAlgorithms *, const char*);
SOAP_FMAC3 struct om__getAlgorithms * SOAP_FMAC4 soap_get_om__getAlgorithms(struct soap*, struct om__getAlgorithms *, const char*, const char*);
SOAP_FMAC3 struct om__getAlgorithms * SOAP_FMAC4 soap_in_om__getAlgorithms(struct soap*, const char*, struct om__getAlgorithms *, const char*);

#ifndef SOAP_TYPE_om__getAlgorithmsResponse
#define SOAP_TYPE_om__getAlgorithmsResponse (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_om__getAlgorithmsResponse(struct soap*, struct om__getAlgorithmsResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_om__getAlgorithmsResponse(struct soap*, const struct om__getAlgorithmsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_om__getAlgorithmsResponse(struct soap*, struct om__getAlgorithmsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_om__getAlgorithmsResponse(struct soap*, struct om__getAlgorithmsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_om__getAlgorithmsResponse(struct soap*, const char*, int, const struct om__getAlgorithmsResponse *, const char*);
SOAP_FMAC3 struct om__getAlgorithmsResponse * SOAP_FMAC4 soap_get_om__getAlgorithmsResponse(struct soap*, struct om__getAlgorithmsResponse *, const char*, const char*);
SOAP_FMAC3 struct om__getAlgorithmsResponse * SOAP_FMAC4 soap_in_om__getAlgorithmsResponse(struct soap*, const char*, struct om__getAlgorithmsResponse *, const char*);

#ifndef SOAP_TYPE_om__Algorithms
#define SOAP_TYPE_om__Algorithms (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_om__Algorithms(struct soap*, struct soap_Algorithms const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_om__Algorithms(struct soap*, const struct soap_Algorithms *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_om__Algorithms(struct soap*, struct soap_Algorithms *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_om__Algorithms(struct soap*, struct soap_Algorithms *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_om__Algorithms(struct soap*, const char*, int, const struct soap_Algorithms *, const char*);
SOAP_FMAC3 struct soap_Algorithms * SOAP_FMAC4 soap_get_om__Algorithms(struct soap*, struct soap_Algorithms *, const char*, const char*);
SOAP_FMAC3 struct soap_Algorithms * SOAP_FMAC4 soap_in_om__Algorithms(struct soap*, const char*, struct soap_Algorithms *, const char*);

#ifndef SOAP_TYPE_soap_Algorithms
#define SOAP_TYPE_soap_Algorithms (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_soap_Algorithms(struct soap*, struct soap_Algorithms const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_soap_Algorithms(struct soap*, const struct soap_Algorithms *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_soap_Algorithms(struct soap*, struct soap_Algorithms *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_soap_Algorithms(struct soap*, struct soap_Algorithms *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_soap_Algorithms(struct soap*, const char*, int, const struct soap_Algorithms *, const char*);
SOAP_FMAC3 struct soap_Algorithms * SOAP_FMAC4 soap_get_soap_Algorithms(struct soap*, struct soap_Algorithms *, const char*, const char*);
SOAP_FMAC3 struct soap_Algorithms * SOAP_FMAC4 soap_in_soap_Algorithms(struct soap*, const char*, struct soap_Algorithms *, const char*);

#ifndef SOAP_TYPE_om__AlgorithmMetadata
#define SOAP_TYPE_om__AlgorithmMetadata (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_om__AlgorithmMetadata(struct soap*, struct soap_AlgorithmMetadata const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_om__AlgorithmMetadata(struct soap*, const struct soap_AlgorithmMetadata *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_om__AlgorithmMetadata(struct soap*, struct soap_AlgorithmMetadata *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_om__AlgorithmMetadata(struct soap*, struct soap_AlgorithmMetadata *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_om__AlgorithmMetadata(struct soap*, const char*, int, const struct soap_AlgorithmMetadata *, const char*);
SOAP_FMAC3 struct soap_AlgorithmMetadata * SOAP_FMAC4 soap_get_om__AlgorithmMetadata(struct soap*, struct soap_AlgorithmMetadata *, const char*, const char*);
SOAP_FMAC3 struct soap_AlgorithmMetadata * SOAP_FMAC4 soap_in_om__AlgorithmMetadata(struct soap*, const char*, struct soap_AlgorithmMetadata *, const char*);

#ifndef SOAP_TYPE_soap_AlgorithmMetadata
#define SOAP_TYPE_soap_AlgorithmMetadata (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_soap_AlgorithmMetadata(struct soap*, struct soap_AlgorithmMetadata const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_soap_AlgorithmMetadata(struct soap*, const struct soap_AlgorithmMetadata *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_soap_AlgorithmMetadata(struct soap*, struct soap_AlgorithmMetadata *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_soap_AlgorithmMetadata(struct soap*, struct soap_AlgorithmMetadata *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_soap_AlgorithmMetadata(struct soap*, const char*, int, const struct soap_AlgorithmMetadata *, const char*);
SOAP_FMAC3 struct soap_AlgorithmMetadata * SOAP_FMAC4 soap_get_soap_AlgorithmMetadata(struct soap*, struct soap_AlgorithmMetadata *, const char*, const char*);
SOAP_FMAC3 struct soap_AlgorithmMetadata * SOAP_FMAC4 soap_in_soap_AlgorithmMetadata(struct soap*, const char*, struct soap_AlgorithmMetadata *, const char*);

#ifndef SOAP_TYPE_om__AlgorithmParameter
#define SOAP_TYPE_om__AlgorithmParameter (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_om__AlgorithmParameter(struct soap*, struct soap_AlgorithmParameter const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_om__AlgorithmParameter(struct soap*, const struct soap_AlgorithmParameter *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_om__AlgorithmParameter(struct soap*, struct soap_AlgorithmParameter *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_om__AlgorithmParameter(struct soap*, struct soap_AlgorithmParameter *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_om__AlgorithmParameter(struct soap*, const char*, int, const struct soap_AlgorithmParameter *, const char*);
SOAP_FMAC3 struct soap_AlgorithmParameter * SOAP_FMAC4 soap_get_om__AlgorithmParameter(struct soap*, struct soap_AlgorithmParameter *, const char*, const char*);
SOAP_FMAC3 struct soap_AlgorithmParameter * SOAP_FMAC4 soap_in_om__AlgorithmParameter(struct soap*, const char*, struct soap_AlgorithmParameter *, const char*);

#ifndef SOAP_TYPE_soap_AlgorithmParameter
#define SOAP_TYPE_soap_AlgorithmParameter (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_soap_AlgorithmParameter(struct soap*, struct soap_AlgorithmParameter const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_soap_AlgorithmParameter(struct soap*, const struct soap_AlgorithmParameter *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_soap_AlgorithmParameter(struct soap*, struct soap_AlgorithmParameter *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_soap_AlgorithmParameter(struct soap*, struct soap_AlgorithmParameter *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_soap_AlgorithmParameter(struct soap*, const char*, int, const struct soap_AlgorithmParameter *, const char*);
SOAP_FMAC3 struct soap_AlgorithmParameter * SOAP_FMAC4 soap_get_soap_AlgorithmParameter(struct soap*, struct soap_AlgorithmParameter *, const char*, const char*);
SOAP_FMAC3 struct soap_AlgorithmParameter * SOAP_FMAC4 soap_in_soap_AlgorithmParameter(struct soap*, const char*, struct soap_AlgorithmParameter *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (79)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (78)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef SOAP_TYPE_PointerToxsd__int
#define SOAP_TYPE_PointerToxsd__int (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__int(struct soap*, int *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToxsd__int(struct soap*, int *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToxsd__int(struct soap*, int **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__int(struct soap*, int **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__int(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToxsd__int(struct soap*, int **, const char*, const char*);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToxsd__int(struct soap*, const char*, int **, const char*);

#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTounsignedByte(struct soap*, unsigned char **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedByte(struct soap*, const char *, int, unsigned char *const*, const char *);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_get_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_in_PointerTounsignedByte(struct soap*, const char*, unsigned char **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__string
#define SOAP_TYPE_PointerToxsd__string (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__string(struct soap*, char **const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToxsd__string(struct soap*, char **const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToxsd__string(struct soap*, char ***);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__string(struct soap*, char ***, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__string(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerToxsd__string(struct soap*, char ***, const char*, const char*);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerToxsd__string(struct soap*, const char*, char ***, const char*);

#ifndef SOAP_TYPE_PointerToom__Output
#define SOAP_TYPE_PointerToom__Output (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToom__Output(struct soap*, struct soap_Output *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToom__Output(struct soap*, struct soap_Output *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToom__Output(struct soap*, struct soap_Output **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToom__Output(struct soap*, struct soap_Output **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToom__Output(struct soap*, const char *, int, struct soap_Output *const*, const char *);
SOAP_FMAC3 struct soap_Output ** SOAP_FMAC4 soap_get_PointerToom__Output(struct soap*, struct soap_Output **, const char*, const char*);
SOAP_FMAC3 struct soap_Output ** SOAP_FMAC4 soap_in_PointerToom__Output(struct soap*, const char*, struct soap_Output **, const char*);

#ifndef SOAP_TYPE_PointerToom__Algorithm
#define SOAP_TYPE_PointerToom__Algorithm (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToom__Algorithm(struct soap*, struct soap_Algorithm *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToom__Algorithm(struct soap*, struct soap_Algorithm *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToom__Algorithm(struct soap*, struct soap_Algorithm **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToom__Algorithm(struct soap*, struct soap_Algorithm **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToom__Algorithm(struct soap*, const char *, int, struct soap_Algorithm *const*, const char *);
SOAP_FMAC3 struct soap_Algorithm ** SOAP_FMAC4 soap_get_PointerToom__Algorithm(struct soap*, struct soap_Algorithm **, const char*, const char*);
SOAP_FMAC3 struct soap_Algorithm ** SOAP_FMAC4 soap_in_PointerToom__Algorithm(struct soap*, const char*, struct soap_Algorithm **, const char*);

#ifndef SOAP_TYPE_PointerToom__Mask
#define SOAP_TYPE_PointerToom__Mask (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToom__Mask(struct soap*, struct soap_Mask *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToom__Mask(struct soap*, struct soap_Mask *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToom__Mask(struct soap*, struct soap_Mask **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToom__Mask(struct soap*, struct soap_Mask **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToom__Mask(struct soap*, const char *, int, struct soap_Mask *const*, const char *);
SOAP_FMAC3 struct soap_Mask ** SOAP_FMAC4 soap_get_PointerToom__Mask(struct soap*, struct soap_Mask **, const char*, const char*);
SOAP_FMAC3 struct soap_Mask ** SOAP_FMAC4 soap_in_PointerToom__Mask(struct soap*, const char*, struct soap_Mask **, const char*);

#ifndef SOAP_TYPE_PointerToom__Maps
#define SOAP_TYPE_PointerToom__Maps (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToom__Maps(struct soap*, struct soap_Maps *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToom__Maps(struct soap*, struct soap_Maps *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToom__Maps(struct soap*, struct soap_Maps **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToom__Maps(struct soap*, struct soap_Maps **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToom__Maps(struct soap*, const char *, int, struct soap_Maps *const*, const char *);
SOAP_FMAC3 struct soap_Maps ** SOAP_FMAC4 soap_get_PointerToom__Maps(struct soap*, struct soap_Maps **, const char*, const char*);
SOAP_FMAC3 struct soap_Maps ** SOAP_FMAC4 soap_in_PointerToom__Maps(struct soap*, const char*, struct soap_Maps **, const char*);

#ifndef SOAP_TYPE_PointerToom__Points
#define SOAP_TYPE_PointerToom__Points (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToom__Points(struct soap*, struct soap_Points *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToom__Points(struct soap*, struct soap_Points *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToom__Points(struct soap*, struct soap_Points **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToom__Points(struct soap*, struct soap_Points **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToom__Points(struct soap*, const char *, int, struct soap_Points *const*, const char *);
SOAP_FMAC3 struct soap_Points ** SOAP_FMAC4 soap_get_PointerToom__Points(struct soap*, struct soap_Points **, const char*, const char*);
SOAP_FMAC3 struct soap_Points ** SOAP_FMAC4 soap_in_PointerToom__Points(struct soap*, const char*, struct soap_Points **, const char*);

#ifndef SOAP_TYPE_PointerToom__Parameter
#define SOAP_TYPE_PointerToom__Parameter (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToom__Parameter(struct soap*, struct soap_Parameter *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToom__Parameter(struct soap*, struct soap_Parameter *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToom__Parameter(struct soap*, struct soap_Parameter **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToom__Parameter(struct soap*, struct soap_Parameter **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToom__Parameter(struct soap*, const char *, int, struct soap_Parameter *const*, const char *);
SOAP_FMAC3 struct soap_Parameter ** SOAP_FMAC4 soap_get_PointerToom__Parameter(struct soap*, struct soap_Parameter **, const char*, const char*);
SOAP_FMAC3 struct soap_Parameter ** SOAP_FMAC4 soap_in_PointerToom__Parameter(struct soap*, const char*, struct soap_Parameter **, const char*);

#ifndef SOAP_TYPE_PointerToom__Map
#define SOAP_TYPE_PointerToom__Map (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToom__Map(struct soap*, struct soap_Map *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToom__Map(struct soap*, struct soap_Map *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToom__Map(struct soap*, struct soap_Map **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToom__Map(struct soap*, struct soap_Map **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToom__Map(struct soap*, const char *, int, struct soap_Map *const*, const char *);
SOAP_FMAC3 struct soap_Map ** SOAP_FMAC4 soap_get_PointerToom__Map(struct soap*, struct soap_Map **, const char*, const char*);
SOAP_FMAC3 struct soap_Map ** SOAP_FMAC4 soap_in_PointerToom__Map(struct soap*, const char*, struct soap_Map **, const char*);

#ifndef SOAP_TYPE_PointerToom__AbsencePoints
#define SOAP_TYPE_PointerToom__AbsencePoints (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToom__AbsencePoints(struct soap*, struct soap_AbsencePoints *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToom__AbsencePoints(struct soap*, struct soap_AbsencePoints *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToom__AbsencePoints(struct soap*, struct soap_AbsencePoints **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToom__AbsencePoints(struct soap*, struct soap_AbsencePoints **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToom__AbsencePoints(struct soap*, const char *, int, struct soap_AbsencePoints *const*, const char *);
SOAP_FMAC3 struct soap_AbsencePoints ** SOAP_FMAC4 soap_get_PointerToom__AbsencePoints(struct soap*, struct soap_AbsencePoints **, const char*, const char*);
SOAP_FMAC3 struct soap_AbsencePoints ** SOAP_FMAC4 soap_in_PointerToom__AbsencePoints(struct soap*, const char*, struct soap_AbsencePoints **, const char*);

#ifndef SOAP_TYPE_PointerToom__PresencePoints
#define SOAP_TYPE_PointerToom__PresencePoints (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToom__PresencePoints(struct soap*, struct soap_PresencePoints *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToom__PresencePoints(struct soap*, struct soap_PresencePoints *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToom__PresencePoints(struct soap*, struct soap_PresencePoints **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToom__PresencePoints(struct soap*, struct soap_PresencePoints **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToom__PresencePoints(struct soap*, const char *, int, struct soap_PresencePoints *const*, const char *);
SOAP_FMAC3 struct soap_PresencePoints ** SOAP_FMAC4 soap_get_PointerToom__PresencePoints(struct soap*, struct soap_PresencePoints **, const char*, const char*);
SOAP_FMAC3 struct soap_PresencePoints ** SOAP_FMAC4 soap_in_PointerToom__PresencePoints(struct soap*, const char*, struct soap_PresencePoints **, const char*);

#ifndef SOAP_TYPE_PointerToom__Point
#define SOAP_TYPE_PointerToom__Point (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToom__Point(struct soap*, struct soap_Point *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToom__Point(struct soap*, struct soap_Point *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToom__Point(struct soap*, struct soap_Point **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToom__Point(struct soap*, struct soap_Point **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToom__Point(struct soap*, const char *, int, struct soap_Point *const*, const char *);
SOAP_FMAC3 struct soap_Point ** SOAP_FMAC4 soap_get_PointerToom__Point(struct soap*, struct soap_Point **, const char*, const char*);
SOAP_FMAC3 struct soap_Point ** SOAP_FMAC4 soap_in_PointerToom__Point(struct soap*, const char*, struct soap_Point **, const char*);

#ifndef SOAP_TYPE_PointerToom__AlgorithmMetadata
#define SOAP_TYPE_PointerToom__AlgorithmMetadata (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToom__AlgorithmMetadata(struct soap*, struct soap_AlgorithmMetadata *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToom__AlgorithmMetadata(struct soap*, struct soap_AlgorithmMetadata *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToom__AlgorithmMetadata(struct soap*, struct soap_AlgorithmMetadata **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToom__AlgorithmMetadata(struct soap*, struct soap_AlgorithmMetadata **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToom__AlgorithmMetadata(struct soap*, const char *, int, struct soap_AlgorithmMetadata *const*, const char *);
SOAP_FMAC3 struct soap_AlgorithmMetadata ** SOAP_FMAC4 soap_get_PointerToom__AlgorithmMetadata(struct soap*, struct soap_AlgorithmMetadata **, const char*, const char*);
SOAP_FMAC3 struct soap_AlgorithmMetadata ** SOAP_FMAC4 soap_in_PointerToom__AlgorithmMetadata(struct soap*, const char*, struct soap_AlgorithmMetadata **, const char*);

#ifndef SOAP_TYPE_PointerToom__AlgorithmParameter
#define SOAP_TYPE_PointerToom__AlgorithmParameter (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToom__AlgorithmParameter(struct soap*, struct soap_AlgorithmParameter *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToom__AlgorithmParameter(struct soap*, struct soap_AlgorithmParameter *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToom__AlgorithmParameter(struct soap*, struct soap_AlgorithmParameter **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToom__AlgorithmParameter(struct soap*, struct soap_AlgorithmParameter **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToom__AlgorithmParameter(struct soap*, const char *, int, struct soap_AlgorithmParameter *const*, const char *);
SOAP_FMAC3 struct soap_AlgorithmParameter ** SOAP_FMAC4 soap_get_PointerToom__AlgorithmParameter(struct soap*, struct soap_AlgorithmParameter **, const char*, const char*);
SOAP_FMAC3 struct soap_AlgorithmParameter ** SOAP_FMAC4 soap_in_PointerToom__AlgorithmParameter(struct soap*, const char*, struct soap_AlgorithmParameter **, const char*);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (6)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__string(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

SOAP_END_NAMESPACE(soap)

#endif

/* end of soapH.h */
