/usr/lib/openmodeller/libaquamaps.so
/usr/lib/openmodeller/libbioclim.so
/usr/lib/openmodeller/libcsm_bs.so
/usr/lib/openmodeller/libdesktop_garp_bs.so
/usr/lib/openmodeller/libdesktop_garp.so
/usr/lib/openmodeller/libenvelope_score.so
/usr/lib/openmodeller/libenvironmental_distance.so
/usr/lib/openmodeller/libgarp_best_subsets.so
/usr/lib/openmodeller/libgarp.so
/usr/lib/openmodeller/libomsvm.so
/usr/lib/openmodeller/libomneuralnet.so
/usr/share/openmodeller/data/aquamaps.db

