.TH libopenmodeller  "January 2015" openModeller 1.5.0
.SH NAME
libopenmodeller \- openModeller Library
.SH SYNOPSIS
.B libopenmodeller
.SH DESCRIPTION
This manual page documents briefly the
.B libopenmodeller
library
.PP
\fBlibopenModeller\fP is an ecological
niche modelling toolbox.
.SH AUTHOR
libopenModeller was written by: 
Mauro E. S. Muñoz <mesmunoz [at] gmail . com>
Renato De Giovanni <renato [at] cria . org . br>
Ricardo Scachetti Pereira <ricardo [at] tdwg . org>
Kevin Ruland
Tim Sutton <tim [at] linfiniti . com>
Peter Brewer <p . w . brewer [at] reading . ac . uk>
Jens Oberender <j . obi [at] troja . net>
Tom Elwertowski
Alexandre Copertino Jardim <alexcj [at] dpi . inpe . br>
Danilo J. S. Bellini <danilo . estagio [at] gmail . com>
Lin, Cheng-Tao <b89605222 [at] ntu . edu . tw>
